version: "3.8"

services:
  characters-db:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
  characters:
    depends_on:
      - characters-db
    build: 
      context: .
      dockerfile: ./docker/microservice.Dockerfile
      target: development
    volumes:
      - ${CHARACTERS_ROOT_DIRECTORY}:/app:rw



